-- Atleita blog posts (platform + organizer scoped)
CREATE TABLE IF NOT EXISTS `blog_posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_uuid` CHAR(36) NOT NULL,
  `slug` VARCHAR(200) NOT NULL,
  `title` VARCHAR(300) NOT NULL,
  `excerpt` TEXT NULL,
  `body_html` MEDIUMTEXT NULL,
  `cover_image_url` VARCHAR(500) NULL,
  `status` ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
  `featured` TINYINT(1) NOT NULL DEFAULT 0,
  `scope` ENUM('platform','organizer') NOT NULL DEFAULT 'platform',
  `organizer_id` INT UNSIGNED NULL,
  `event_id` INT UNSIGNED NULL,
  `author_admin_id` INT UNSIGNED NULL,
  `author_member_id` INT UNSIGNED NULL,
  `author_name` VARCHAR(200) NULL,
  `seo_title` VARCHAR(300) NULL,
  `seo_description` VARCHAR(500) NULL,
  `og_image_url` VARCHAR(500) NULL,
  `read_time_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 5,
  `locale` VARCHAR(5) NOT NULL DEFAULT 'es',
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_blog_posts_slug` (`slug`),
  UNIQUE KEY `uk_blog_posts_public_uuid` (`public_uuid`),
  KEY `idx_blog_posts_status_published` (`status`, `published_at`),
  KEY `idx_blog_posts_organizer` (`organizer_id`),
  KEY `idx_blog_posts_event` (`event_id`),
  KEY `idx_blog_posts_deleted` (`deleted_at`),
  CONSTRAINT `fk_blog_posts_organizer` FOREIGN KEY (`organizer_id`) REFERENCES `organizers` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_blog_posts_event` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_blog_posts_author_admin` FOREIGN KEY (`author_admin_id`) REFERENCES `admins` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_blog_posts_author_member` FOREIGN KEY (`author_member_id`) REFERENCES `organizer_members` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
